Import('env', 'sys', 'plugins')

plugins += env.SharedLibrary('adaptive', ['misc/adaptive.cpp'])
plugins += env.SharedLibrary('path', ['path/path.cpp'])
plugins += env.SharedLibrary('volpath', ['path/volpath.cpp'])
plugins += env.SharedLibrary('volpath_simple', ['path/volpath_simple.cpp'])
plugins += env.SharedLibrary('photonrt',['photonrt/photonrt.cpp','photonrt/photonrt_proc.cpp'])

#plugins += env.SharedLibrary('lidar', ['lidar/lidar.cpp'])

plugins += env.SharedLibrary('myIntegrator', ['myIntegrator.cpp'])
plugins += env.SharedLibrary('weight', ['weight/weight.cpp'])
plugins += env.SharedLibrary('waveform', ['lidar/waveform.cpp', 'lidar/lidarsampler.cpp', 'lidar/lidarutils.cpp'])

Export('plugins')
